(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Labusr, Welcome to Coot version 0.9.5")
(use-graphics-interface-state)
(set-symmetry-colour 255.00 35.00 0.00)
(set-auto-fit-best-rotamer-clash-flag 1)
(set-add-terminal-residue-n-phi-psi-trials 1000)
(set-active-map-drag-flag 0)
(set-density-size 20.00)
(set-add-terminal-residue-do-post-refine 1)
(set-terminal-residue-do-rigid-body-refine 0)
(set-mutate-auto-fit-do-post-refine 1)
(set-symmetry-size 30.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon labusr. Welcome to Coot 0.9.5")
(set-display-lists-for-maps 1)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 12.60)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle 1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/home/labusr/Desktop/Data2/Corbin/OJ_Modeling/B1_middle_coot-2_3dimers_03-coot-2.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/home/labusr/Desktop/Data2/Corbin/OJ_Modeling/OJ3_3_sharpened.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/home/labusr/Desktop/Data2/Corbin/OJ_Modeling/OJ3_3_sharpened.mtz" "/crystal/dataset/F" "/crystal/dataset/PHIF" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-redo)
(apply-redo)
(apply-redo)
(apply-redo)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(apply-undo)
(apply-redo)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(apply-redo)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/home/labusr/Desktop/Data2/Corbin/OJ_Modeling/B1_middle_coot-2_3dimers_03-coot-0_1b_1.pdb" 1)
(set-go-to-atom-molecule 2)
(update-go-to-atom-window-on-other-molecule-chosen)
(set-go-to-atom-molecule 0)
(graphics-molecule-bond-type 0)
(graphics-molecule-bond-type 2)
(close-molecule 2)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(first-coords-imol)
(first-unsaved-coords-imol)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(first-coords-imol)
(first-unsaved-coords-imol)
(apply-undo)
(apply-undo)
(apply-redo)
(apply-redo)
(apply-undo)
(apply-undo)
(apply-redo)
(apply-redo)
(apply-undo)
(apply-undo)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(apply-redo)
(apply-undo)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(apply-redo)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-redo)
(apply-redo)
(apply-redo)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(show-select-map-dialog)
(show-select-map-dialog)
(set-go-to-atom-molecule 0)
(first-coords-imol)
(first-unsaved-coords-imol)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(apply-undo)
(apply-undo)
(apply-redo)
(apply-redo)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(first-coords-imol)
(first-unsaved-coords-imol)
(graphics-molecule-bond-type 0)
